baseURL = "https://kuzaxak.dev/"
languageCode = "en-us"
title = "Vladimir Kuznichenkov | Engineer"
author = "Vladimir Kuznichenkov"
theme = "archie"
copyright = "© Vladimir Kuznichenkov"

# get information about the Git repo, such as last commit to a file
enableGitInfo = true

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10

googleAnalytics = 'G-6MR97DTEQB'
enableRobotsTXT = true

[params]
  mode = "toggle"
  author = "Vladimir Kuznichenkov"
  description = """Hi, my name is Vladimir Kuznichenkov. I am a Senior Infrastructure Engineer.
    This blog is my attempt to synthesize and share what I’ve learned along the way.
    Mainly, I'll share blog posts related to Infrastructure, Firmware, and Hardware."""
  copyright = "@ Vladimir Kuznichenkov"
  WebMentionDomain = "kuzaxak.dev"
  mathjax = false # enable MathJax support
  katex = false # enable KaTeX support
  ShowFullTextinRSS = true

# Social Tags
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/kuzaxak/blog"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/kuzaxak/"

[social]
  twitter = 'kuzaxak'

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"
  tags = "/tags/:title/"


[outputFormats]

[outputFormats.rss]
  mediatype = "application/rss"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
    typographer = false
    [markup.goldmark.renderer]
    # allow inline HTML, such as spoiler warnings
    unsafe = true
  [markup.tableOfContents]
  startLevel = 1
  endLevel = 6
  ordered = false


[menu]
  [[menu.main]]
    identifier = "blog"
    name = "./blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "./about"
    url = "/about"
    weight = 3


  [[menu.footer]]
    name = "Tags"
    url = "/tags"
    weight = 4


[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
